[supervisord]
nodaemon=true
logfile=%(here)s/supervisord.log
pidfile=%(here)s/supervisord.pid

[supervisorctl]
# supervisorctl 必須能夠找到 serverurl
# 我們可以透過 unix socket 或 http server 來做到
# 這裡我們使用 http server，因為它更簡單
serverurl=http://127.0.0.1:9001

[inet_http_server]
port=127.0.0.1:9001

[program:worker_A]
command=/usr/bin/python3 -m uv run --script %(here)s/worker_A.py
process_name=%(program_name)s
autostart=true
autorestart=true
startretries=5
stdout_logfile=%(here)s/worker_A_stdout.log
stderr_logfile=%(here)s/worker_A_stderr.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1

[program:worker_B]
command=/usr/bin/python3 -m uv run --script %(here)s/worker_B.py
process_name=%(program_name)s
autostart=true
autorestart=true
startretries=5
stdout_logfile=%(here)s/worker_B_stdout.log
stderr_logfile=%(here)s/worker_B_stderr.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
